version: "3.5"

networks:
  remote-build_remote-server:
    external: true

services:
  angular_a:
    build: .
    command: bash -c "tail -f /dev/null"
    ports:
      - "3010:5432"
      - "35729:35729"
    container_name: angular_a
    volumes:
      - ../angular-demo:/usr/demo
    networks:
       remote-build_remote-server:
  angular_b:
    build: .
    command: bash -c "tail -f /dev/null"
    ports:
      - "3011:5432"
    container_name: angular_b
    volumes:
      - ../angular-demo:/usr/demo
    networks:
       remote-build_remote-server:      
    
