version: "3.5"

networks:
  remote-server:
    driver: bridge

services:
  remote_server:
    build: .
    command: bash -c "bazel build //src/main/java/build/buildfarm:buildfarm-server && bazel-bin/src/main/java/build/buildfarm/buildfarm-server examples/server.config"
    container_name: remote_server
    networks:
      remote-server:
         aliases:
          - remote
    ports:
      - "8980:8980"