version: "3.5"

networks:
  remote-server:
    driver: bridge

services:
  remote_server:
    build: .
    command: ./server.sh
    container_name: remote_server
    networks:
      remote-server:
         aliases:
          - remote
    ports:
      - "8980:8980"