version: "3.5"

networks:
  remote-build_remote-server:
    external: true

services:
  remote_worker:
    build: .
    command: ./worker.sh
    container_name: remote_worker
    networks:
      remote-build_remote-server: